name: Build and release

on:
  push:
    branches:
      - main
    tags:
      - v?[0-9]+.[0-9]+.[0-9]+ # semver
      - '!dev-build' # not dev-build

jobs:
  build:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/build_artifacts.yml
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Downloads artifacts
        uses: actions/download-artifact@v4
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: uad-ng-*/*
          generate_release_notes: true
          body: |
            > [!NOTE]
            > ğŸ“¦ **Package list updates don't require a new app version**â€”UAD-ng automatically fetches the latest package definitions on launch (requires internet connection).
